### ISSUE TITLE
企業のコントローラーはCHENに任せます。

### ISSUE THREAD

**Issue by dmo101** [Chingishitsu/Mickey-Works#3]
詳細な書き方はWIKIの管理者のコントローラーを参考してください。

**Comment by dmo101** [comment]
管理者コントローラーの名前はAdminControllerを命名してください。

**Comment by hipapa** [comment]
企業登録画面を作っています。
コントローラーとバリデーションは完成していますが、
バリテーションとBootstrapのform-controlはちょっとコンフリクトがあります。

**Comment by hipapa** [comment]
企業詳細情報画面でマッチング情報により、学生IDの取得は失敗しました。

**Comment by hipapa** [comment]
完成しました
